batch_size: 32
epochs: 3000
epochs_til_checkpoint: 100
experiment_name: airplane_relu
hidden_num: 128
logging_root: ./exp_render/logs
lr: 0.0001
model_type: relu
batch_max: 4000
steps_til_summary: 200
checkpoint_path: ./exp_render/logs/airplane_relu/checkpoints/model_current.pth
mat_path: ./exp_render/datasets/airplane.mat
net: sim_RDF
source_mesh: ./exp_render/model3d/airplane.obj