batch_size: 32
epochs: 3000
epochs_til_checkpoint: 100
experiment_name: Hilb64_relu
hidden_num: 128
logging_root: ./exp_render/logs
lr: 0.0001
model_type: relu
batch_max: 4000
steps_til_summary: 200
checkpoint_path: ./exp_render/logs/Hilb64_relu/checkpoints/model_current.pth
mat_path: exp_render/datasets/Hilb64.mat
net: sim_RDF
source_mesh: ./exp_render/model3d/Hilb64.stl