batch_size: 64
epochs: 5000
epochs_til_checkpoint: 100
experiment_name: airplane_1
hidden_num: 128
logging_root: ./exp_render/logs
lr: 0.0001
model_type: sine
batch_max: 8000
steps_til_summary: 200
checkpoint_path: ./exp_render/logs/airplane_1/checkpoints/model_current.pth
mat_path: datasets/airplane/196d35794f869816db6f03b6829a5891.mat
