batch_size: 32
epochs: 5000
epochs_til_checkpoint: 100
experiment_name: dress
hidden_num: 128
logging_root: ./exp_render/logs
lr: 0.0001
model_type: sine
batch_max: 16000
steps_til_summary: 200
checkpoint_path: ./exp_render/logs/dress/checkpoints/model_current.pth
mat_path: ./exp_render/datasets/dress.mat
net: sim_RDF