batch_size: 32
epochs: 5000
epochs_til_checkpoint: 100
experiment_name: long_sleeve_upper
hidden_num: 128
logging_root: ./exp_render/logs
lr: 0.0001
model_type: sine
batch_max: 16000
steps_til_summary: 200
checkpoint_path: ./exp_render/logs/long_sleeve_upper/checkpoints/model_current.pth
mat_path: exp_render/datasets/long_sleeve_upper.mat
net: sim_RDF
source_mesh: ./exp_render/model3d/long_sleeve_upper.obj