batch_size: 32
epochs: 3000
epochs_til_checkpoint: 100
experiment_name: airplane_SDF
hidden_num: 128
logging_root: ./exp_render/logs
lr: 0.0001
model_type: sine
batch_max: 4000
steps_til_summary: 200
checkpoint_path: ./exp_render/logs/airplane_SDF/checkpoints/model_current.pth
mat_path: ./exp_render/datasets/airplane_sdf.mat
net: sim_SDF