batch_size: 256
epochs: 500
epochs_til_checkpoint: 100
expand: -1
experiment_name: 02747177_ODF
hidden_num: 128
latent_dim: 128
logging_root: ./logs
lr: 0.0001
model_type: relu
num_instances: 220
batch_max: 8000
loss_grad_deform: 5
mat_path: datasets/02747177
steps_til_summary: 500
train_split: split/train/02747177.txt
checkpoint_path: logs/02747177_ODF/checkpoints/model_current.pth
net: OmniDistanceField