batch_size: 64
epochs: 500
epochs_til_checkpoint: 100
expand: -1
experiment_name: airplane_ODF
hidden_num: 128
latent_dim: 128
logging_root: ./logs
lr: 0.0001
model_type: sine
num_instances: 273
batch_max: 40000
loss_grad_deform: 500
mat_path: datasets/airplane
steps_til_summary: 500
train_split: split/train/airplane.txt
checkpoint_path: logs/airplane_ODF/checkpoints/model_current.pth
net: OmniDistanceField