batch_size: 128
epochs: 200
epochs_til_checkpoint: 100
expand: -1
experiment_name: long_pants_RDF
hidden_num: 128
latent_dim: 128
logging_root: ./logs
model_type: sine
num_instances: 33
batch_max: 5000
loss_grad_deform: 100
mat_path: datasets/long_pants
steps_til_summary: 500
train_split: split/train/long_pants.txt
checkpoint_path: logs/long_pants_RDF/checkpoints/model_current.pth
net: RayDistanceField
lr: 0.0001