batch_size: 16
epochs: 200
epochs_til_checkpoint: 100
expand: -1
experiment_name: T11
hidden_num: 128
latent_dim: 128
logging_root: ./logs
lr: 0.0001
model_type: sine
num_instances: 50
batch_max: 4000
loss_grad_deform: 5
mat_path: datasets/11_Outside
steps_til_summary: 500
train_split: split/train/11_Outside.txt
checkpoint_path: logs/11_Outside/checkpoints/model_current.pth
