batch_size: 128
epochs: 500
epochs_til_checkpoint: 100
expand: -1
experiment_name: T11_RDF
hidden_num: 128
latent_dim: 128
logging_root: ./logs
lr: 0.0001
model_type: sine
num_instances: 50
batch_max: 5000
loss_grad_deform: 5
mat_path: datasets/T11
steps_til_summary: 500
train_split: split/train/T11.txt
checkpoint_path: logs/T11_RDF/checkpoints/model_current.pth
net: RayDistanceField