batch_size: 256
epochs: 500
epochs_til_checkpoint: 100
expand: -1
experiment_name: T11_relu
hidden_num: 128
latent_dim: 128
logging_root: ./logs
lr: 0.0001
model_type: relu
num_instances: 50
batch_max: 6000
loss_grad_deform: 5
mat_path: datasets/T11
steps_til_summary: 500
train_split: split/train/T11.txt
checkpoint_path: logs/T11_relu/checkpoints/model_current.pth
