batch_size: 128
epochs: 200
epochs_til_checkpoint: 100
expand: -1
experiment_name: T15_RDF
hidden_num: 128
latent_dim: 128
logging_root: ./logs
lr: 0.0001
model_type: sine
num_instances: 54
batch_max: 5000
loss_grad_deform: 100
mat_path: datasets/T15
steps_til_summary: 500
train_split: split/train/T15.txt
checkpoint_path: logs/T15_RDF/checkpoints/model_current.pth
net: RayDistanceField