batch_size: 128
epochs: 200
epochs_til_checkpoint: 100
expand: -1
experiment_name: table_RDF
hidden_num: 128
latent_dim: 128
logging_root: ./logs
model_type: sine
num_instances: 173
batch_max: 5000
loss_grad_deform: 100
mat_path: datasets/table
steps_til_summary: 500
train_split: split/train/table.txt
checkpoint_path: logs/table_RDF/checkpoints/model_current.pth
net: RayDistanceField
lr: 0.0001